#!/bin/bash
#
# BipPass — 165.22.176.141
#
#   ./bippass.sh            ssh in
#   ./bippass.sh provision  swapfile, /srv/bippass, generated .env  (ONCE, first run)
#   ./bippass.sh status     containers, health, memory
#   ./bippass.sh logs [svc] tail the logs
#   ./bippass.sh deploy     rebuild locally, ship the images, restart
#   ./bippass.sh build      build the images without shipping them
#   ./bippass.sh mail-key   prompt for the Resend API key and store it on the server
#
# A dedicated droplet, unlike EVO-Connect's — nothing else runs here. It is still 1 vCPU
# / 957 MB and cannot build any of this: a Go workspace spread over 25 modules, and a
# Vite build of six federation bundles. Images are built on the workstation and shipped
# over SSH — no registry, and no source on the server. /srv/bippass holds only a compose
# file and an .env of generated secrets.
#
# Caddy terminates TLS on 80/443 for bippass.com (web) and api.bippass.com (api) and is
# the only service on the public interface. web, api, postgres and redis publish no host
# ports at all.
set -euo pipefail

# Absolute, because `build` cd's into the repo trees to run docker build. A relative $0
# stops resolving the moment the working directory changes — which is how `deploy` used to
# die on its very last line, reporting a failure after having already deployed successfully.
SELF=$(cd "$(dirname "$0")" && pwd)/$(basename "$0")

HOST=root@165.22.176.141
REMOTE=/srv/bippass
REPO=${BIPPASS_REPO:-$HOME/work/personal/bippass}

# The browser talks to both of these directly, so they are the droplet's public address
# rather than compose service names, and the API origin must differ from the web origin.
PUBLIC_ORIGIN=${PUBLIC_ORIGIN:-https://bippass.com}
API_ORIGIN=${API_ORIGIN:-https://api.bippass.com}

IMAGES=(bippass-api bippass-worker bippass-migrate bippass-web)

build() {
  local version be_rev fe_rev
  version=$(git -C "$REPO/bippass-backend" describe --tags --always --dirty 2>/dev/null || echo dev)

  # The commit each image is built from, stamped as an OCI label so `status` can tell you
  # whether what is RUNNING matches what is COMMITTED. Nothing linked the two before, and
  # the gap is not theoretical: the Ciphertext wordmark and an nginx fix both sat committed
  # and undeployed for hours on 2026-08-22, found by someone asking rather than by a check.
  # Two revisions because the deployment spans two repos: api/worker/migrate come from
  # bippass-backend, web from bippass-frontend.
  be_rev=$(git -C "$REPO/bippass-backend" rev-parse --short HEAD 2>/dev/null || echo unknown)
  fe_rev=$(git -C "$REPO/bippass-frontend" rev-parse --short HEAD 2>/dev/null || echo unknown)

  # api/worker/migrate share one Dockerfile; BINARY picks the cmd. The context is
  # bippass-backend, whose go.work + local replaces are what make the modules resolve —
  # none of them builds alone.
  cd "$REPO/bippass-backend"
  for b in api worker migrate; do
    echo "==> bippass-$b"
    docker build --build-arg "BINARY=$b" --build-arg "VERSION=$version" \
      --label "org.opencontainers.image.revision=$be_rev" -t "bippass-$b:latest" .
  done

  # The web build context is the repo PARENT: apps/web depends on @bippass/ui through a
  # link: path into the sibling bippass-ui checkout. VITE_* are inlined at build time, so
  # the droplet's URLs are fixed here and cannot be changed by a restart.
  echo "==> bippass-web"
  cd "$REPO"
  docker build -f bippass-frontend/Dockerfile \
    --build-arg "PUBLIC_ORIGIN=$PUBLIC_ORIGIN" \
    --build-arg "VITE_API_URL=$API_ORIGIN/api/v1" \
    --label "org.opencontainers.image.revision=$fe_rev" \
    -t bippass-web:latest .
}

case "${1:-shell}" in
  shell)
    exec ssh "$HOST"
    ;;

  provision)
    ssh "$HOST" "mkdir -p $REMOTE"
    scp "$REPO/bippass-backend/deploy/docker-compose.prod.yml" "$HOST:$REMOTE/docker-compose.yml"
    scp "$REPO/bippass-backend/deploy/Caddyfile" "$HOST:$REMOTE/Caddyfile"
    # Secrets are generated ON THE SERVER and never printed here: the master key is what
    # every sealed client secret and envelope-encrypted value depends on, so it should
    # exist in exactly one place.
    ssh "$HOST" "PUBLIC_ORIGIN='$PUBLIC_ORIGIN' API_ORIGIN='$API_ORIGIN' REMOTE='$REMOTE' bash -s" <<'PROVISION'
set -euo pipefail

# The droplet ships with no swap. With 957 MB and no swap, memory pressure is not a
# slowdown, it is the OOM killer picking a process. 2 GB of swap turns the first class of
# incident into the second-to-last.
if ! swapon --show | grep -q .; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  echo "added 2G swapfile"
fi

if [ -f "$REMOTE/.env" ]; then
  echo "$REMOTE/.env already exists — refusing to regenerate."
  echo "A new BIPPASS_MASTER_KEY cannot decrypt anything sealed under the old one."
  exit 0
fi

umask 077
cat > "$REMOTE/.env" <<EOF
# Generated by bippass.sh provision. BIPPASS_MASTER_KEY is unrecoverable — every sealed
# client secret and envelope-encrypted value depends on it. Back it up before you rely
# on this instance for anything.
APP_NAME=BipPass
APP_ENV=staging
LOG_LEVEL=info
HTTP_ADDR=:8080

DB_DATABASE=bippass
DB_USERNAME=bippass
DB_PASSWORD=$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)
DB_MAX_CONNS=10
DB_MIN_CONNS=2

REDIS_DB=0

BIPPASS_KMS_DRIVER=local
BIPPASS_MASTER_KEY=$(head -c 32 /dev/urandom | base64)

# Reachable addresses, not service names: a browser resolves these, not the compose
# network. PUBLIC_URL is the API base (redirect_uri, absolute links in mail); WEB_URL is
# where a person is returned to after SSO. Without WEB_URL every /auth/sso/* route
# answers 404, which reads as "the feature is missing".
PUBLIC_URL=$API_ORIGIN
WEB_URL=$PUBLIC_ORIGIN
CORS_ALLOWED_ORIGINS=$PUBLIC_ORIGIN
CORS_ALLOW_CREDENTIALS=true

ACCESS_TOKEN_TTL=1h
REFRESH_TOKEN_TTL=720h

RATE_LIMIT_ENABLED=true
RATE_LIMIT_MODE=enforce
RATE_LIMIT_PER_MIN=600
RATE_LIMIT_BURST=100
RATE_LIMIT_AUTH_PER_MIN=10
RATE_LIMIT_AUTH_BURST=5

# Resend over SMTP. Port 587 is not a preference: core/mail sends via Go's
# smtp.SendMail, which opens plaintext and upgrades with STARTTLS — it cannot do implicit
# TLS, so 465 would simply fail. The username is the literal string "resend"; the password
# is an API key.
#
# Mail.Configured() requires BOTH host and from-address to be non-empty. Leave
# MAIL_PASSWORD unset and the app still boots and still "sends" — Resend rejects the auth
# and the error is only logged, because sendVerificationEmail is best-effort by design.
# So an unset key looks exactly like a working one until someone reports a missing email.
MAIL_HOST=smtp.resend.com
MAIL_PORT=587
MAIL_USERNAME=resend
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=no-reply@bippass.com
MAIL_FROM_NAME=BipPass

# Stays false until mail is confirmed working end to end. With it true and no MAIL_HOST
# the app refuses to boot — deliberately, because every new device would be locked out
# permanently with no way to deliver the verification link.
DEVICE_TRUST_ENFORCED=false

# The OTel collector is a local-only compose service; there is nothing to export to here.
OTEL_ENABLED=false

# Empty STRIPE_SECRET disables paid plans entirely, which is correct: the plan rows still
# carry placeholder price ids (price_basic_monthly), not real Stripe ones.
STRIPE_SECRET=
EOF
chmod 600 "$REMOTE/.env"
echo "wrote $REMOTE/.env (0600)"
PROVISION
    echo "provisioned. now: $SELF deploy"
    ;;

  mail-key)
    # Prompts on the SERVER and writes straight to .env. The key goes from your keyboard
    # to the file: never through an argument (visible in ps), never through the local
    # shell's history, never through a chat window. Prints the stored LENGTH as
    # confirmation — the previous attempt silently stored an empty value, and an empty
    # MAIL_PASSWORD looks identical to a working one until someone reports a missing
    # email, because sendVerificationEmail only logs its failures.
    ssh -t "$HOST" 'cd /srv/bippass \
      && read -rsp "Resend API key (input hidden): " KEY && echo \
      && if [ -z "$KEY" ]; then echo "empty — nothing written"; exit 1; fi \
      && sed -i "s|^MAIL_PASSWORD=.*|MAIL_PASSWORD=$KEY|" .env \
      && unset KEY \
      && awk -F= "/^MAIL_PASSWORD=/{print \"stored, value length \" length(\$2)}" .env \
      && docker compose up -d api worker'
    ;;

  build)
    build
    docker images --filter=reference='bippass-*' --format 'table {{.Repository}}\t{{.Tag}}\t{{.Size}}'
    ;;

  deploy)
    build

    # Ship the compose file too, so the server's copy is never ahead of the repo's.
    scp "$REPO/bippass-backend/deploy/docker-compose.prod.yml" "$HOST:$REMOTE/docker-compose.yml"
    scp "$REPO/bippass-backend/deploy/Caddyfile" "$HOST:$REMOTE/Caddyfile"

    echo "shipping images (~135 MB uncompressed, gzipped in flight)…"
    docker save "${IMAGES[@]/%/:latest}" | gzip -1 | ssh "$HOST" 'gunzip | docker load'

    # `up -d` rather than `restart`: migrate is a dependency with
    # condition: service_completed_successfully, and only `up` evaluates that. A restart
    # would start the api against whatever schema happened to be there.
    echo "restarting…"
    ssh "$HOST" "cd $REMOTE && docker compose up -d"

    sleep 8
    "$SELF" status
    ;;

  logs)
    ssh "$HOST" "cd $REMOTE && docker compose logs -f --tail=200 ${2:-}"
    ;;

  status)
    ssh "$HOST" "cd $REMOTE && docker compose ps --format 'table {{.Service}}\t{{.Status}}'"
    echo
    curl -fsS -m 15 -o /dev/null -w "web = %{http_code}\n" "$PUBLIC_ORIGIN/healthz" || echo "web = DOWN"
    # A 404 from the SSO lookup is a HEALTHY answer for an unknown domain — it proves the
    # route is mounted, which is the thing that silently breaks when WEB_URL is unset.
    curl -sS -m 15 -o /dev/null -w "api = %{http_code} (200 expected; 404 means WEB_URL is unset)\n" \
      "$API_ORIGIN/api/v1/auth/sso/lookup?domain=probe.invalid" || echo "api = DOWN"
    echo -n "cert = "; curl -sS -m 15 -o /dev/null -w "%{ssl_verify_result} (0 = trusted)\n" "$PUBLIC_ORIGIN/healthz" || echo "no TLS"
    echo
    ssh "$HOST" "free -m | awk 'NR==1||/Mem:|Swap:/'; echo; docker stats --no-stream --format 'table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.CPUPerc}}'"

    # Is what is RUNNING what is COMMITTED?
    #
    # Every other line above reports that the deployment is healthy. Healthy and current
    # are different questions, and only this one answers the second. On 2026-08-22 the site
    # was green while serving a three-hour-old image; the fix had been committed and pushed
    # and simply never deployed, and nothing here would have said so.
    echo
    echo "deployed vs committed:"
    running=$(ssh "$HOST" 'for c in bippass-api-1 bippass-web-1; do
        printf "%s %s\n" "$c" "$(docker inspect "$c" --format "{{index .Config.Labels \"org.opencontainers.image.revision\"}}" 2>/dev/null)"
      done' 2>/dev/null)

    check_rev() {
      local label="$1" repo="$2" container="$3"
      local deployed local_head behind
      deployed=$(printf '%s\n' "$running" | awk -v c="$container" '$1==c{print $2}')
      local_head=$(git -C "$REPO/$repo" rev-parse --short HEAD 2>/dev/null || echo "?")

      if [ -z "$deployed" ] || [ "$deployed" = "<no value>" ]; then
        printf '  %-9s running image predates provenance labels — redeploy to start tracking\n' "$label"
        return
      fi
      if [ "$deployed" = "$local_head" ]; then
        printf '  %-9s %s — current\n' "$label" "$deployed"
      else
        # How far behind, when the deployed commit is still known locally.
        behind=$(git -C "$REPO/$repo" rev-list --count "$deployed..HEAD" 2>/dev/null || echo "?")
        printf '  %-9s %s — STALE, %s commit(s) behind %s · run: %s deploy\n' \
          "$label" "$deployed" "$behind" "$local_head" "$SELF"
      fi
    }

    check_rev "backend" "bippass-backend" "bippass-api-1"
    check_rev "frontend" "bippass-frontend" "bippass-web-1"
    ;;

  *)
    echo "usage: $SELF [shell|provision|build|deploy|logs [service]|status]" >&2
    exit 2
    ;;
esac
