#!/bin/bash
#
# LinkedIn Poster — 165.22.176.141 (shared with BipPass and ApplyBuddy)
#   https://linkedin.applybuddy.net
#
#   ./linkedin.sh            ssh in
#   ./linkedin.sh provision  /srv/linkedin-poster and a starter .env  (ONCE, first run)
#   ./linkedin.sh keys       prompt for OPEN_CODE_KEY and store it on the server
#   ./linkedin.sh keys local copy OPEN_CODE_KEY from your shell / ~/.bashrc / repo .env
#   ./linkedin.sh build      build the image without shipping it
#   ./linkedin.sh deploy     rebuild locally, ship the image, restart
#   ./linkedin.sh expose     put linkedin.applybuddy.net on Caddy  (ONCE, after DNS)
#   ./linkedin.sh status     container, health, memory, deployed-vs-committed
#   ./linkedin.sh logs       tail the logs
#   ./linkedin.sh backup     download the data volume (conversations, history, voice)
#
# THIS DROPLET IS BIPPASS'S, and BipPass takes money. Same three rules as ApplyBuddy
# (see deploy/docker-compose.prod.yml in the repo): a separate compose project on
# BipPass's network as EXTERNAL, a prefixed alias (`linkedin-poster`), and a hard memory
# limit so a runaway here restarts this container instead of starving the box.
#
# Posting uses "Share on LinkedIn" links (PUBLISH_MODE=share): the app opens LinkedIn's
# composer pre-filled and the person presses Post. So there is NO LinkedIn app, OAuth or
# token on this server — the only secret is the model key.
#
# The site is public with no login (by choice): anyone with the URL can run agents on
# this key's quota, but nobody can post to LinkedIn through it.
#
# Caddy, the network and everything else belong to the BipPass compose project; this
# script never creates or destroys any of them. The one file it needs in the BipPass repo
# is the linkedin.applybuddy.net site block in its Caddyfile — see `expose`.
set -euo pipefail

SELF=$(cd "$(dirname "$0")" && pwd)/$(basename "$0")

HOST=root@165.22.176.141
REMOTE=/srv/linkedin-poster
REPO=${LINKEDIN_POSTER_REPO:-$HOME/work/personal/ai/linkedin-poster}
IMAGE=linkedin-poster
CONTAINER=linkedin-poster
SITE_HOST=linkedin.applybuddy.net
SITE_ORIGIN=https://$SITE_HOST

BIPPASS_REPO=${BIPPASS_REPO:-$HOME/work/personal/bippass}
BIPPASS_REMOTE=/srv/bippass
BIPPASS_CADDYFILE=$BIPPASS_REPO/bippass-backend/deploy/Caddyfile

# One multiplexed SSH connection for every ssh/scp below. The droplet rate-limits new SSH
# connections, and deploy + status open about ten in quick succession — without this the
# later ones are refused ("Connection refused") mid-deploy.
SSH_CONTROL="${TMPDIR:-/tmp}/linkedin-sh-%C"
ssh() { command ssh -o ControlMaster=auto -o ControlPath="$SSH_CONTROL" -o ControlPersist=120s "$@"; }
scp() { command scp -o ControlMaster=auto -o ControlPath="$SSH_CONTROL" -o ControlPersist=120s "$@"; }

require_provisioned() {
  ssh "$HOST" "test -f $REMOTE/.env" || {
    echo "not provisioned yet — run: $SELF provision" >&2
    exit 1
  }
}

revision() {
  local rev
  rev=$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)
  # Uncommitted changes are code in the image with no commit behind it: say so.
  if [ -n "$(git -C "$REPO" status --porcelain 2>/dev/null)" ]; then rev="$rev+dirty"; fi
  echo "$rev"
}

build() {
  local rev
  rev=$(revision)
  echo "building $IMAGE ($rev) for linux/amd64…"
  docker build --platform linux/amd64 \
    --label "org.opencontainers.image.revision=$rev" \
    -t "$IMAGE:latest" "$REPO"
}

# Merge NAME=VALUE lines from stdin into the server's .env. The script goes in the ssh
# COMMAND (base64) and the values over ssh's STDIN — never as arguments (ps would show
# them), never printed, never expanded by either shell. Only names and lengths appear.
MERGE_ENV=$(base64 -w0 <<'MERGE'
cd /srv/linkedin-poster || exit 1
umask 077
touch .env
while IFS= read -r line; do
  [ -n "$line" ] || continue
  name=${line%%=*}
  { grep -v "^${name}=" .env || true; printf '%s\n' "$line"; } > .env.tmp
  mv .env.tmp .env
  echo "  $name stored (${#line} chars)"
done
chmod 600 .env
MERGE
)

case "${1:-shell}" in
  shell)
    exec ssh "$HOST"
    ;;

  provision)
    ssh "$HOST" "mkdir -p $REMOTE && docker network inspect bippass >/dev/null" || {
      echo "the 'bippass' network is missing — is the BipPass stack running?" >&2
      exit 1
    }
    ssh "$HOST" "REMOTE='$REMOTE' SITE_ORIGIN='$SITE_ORIGIN' bash -s" <<'PROVISION'
set -e
cd "$REMOTE"
if [ -f .env ]; then
  echo ".env already exists — left untouched"
else
  umask 077
  cat > .env <<ENV
# Generated by linkedin.sh provision. Secrets are added by: linkedin.sh keys
OPEN_CODE_KEY=
DEFAULT_MODEL=space-bunny-free
# Tried in order if the model is removed or blocked (free models rotate):
LLM_FALLBACK_MODELS=
PUBLISH_MODE=share
# Public site, shared quota: keep the per-turn budgets tight.
MAX_LLM_CALLS_PER_RUN=30
MAX_SEARCHES_PER_RUN=6
ENV
  echo "wrote $REMOTE/.env"
fi
PROVISION
    echo "next: $SELF keys   (then: $SELF deploy)"
    ;;

  keys)
    require_provisioned
    if [ "${2:-}" = local ]; then
      key=${OPEN_CODE_KEY:-}
      if [ -z "$key" ] && [ -f "$HOME/.bashrc" ]; then
        # The export line itself, not `bash -ic`: anything .bashrc prints would end up in the key.
        key=$(grep -E '^[[:space:]]*export[[:space:]]+OPEN_CODE_KEY=' "$HOME/.bashrc" | tail -1 \
          | sed -E 's/^[^=]*=//; s/^["'"'"']//; s/["'"'"']$//' || true)
      fi
      if [ -z "$key" ] && [ -f "$REPO/.env" ]; then
        key=$(grep -E '^OPEN_CODE_KEY=' "$REPO/.env" | tail -1 | cut -d= -f2-)
      fi
      [ -n "$key" ] || { echo "OPEN_CODE_KEY not found in your shell, ~/.bashrc or $REPO/.env" >&2; exit 1; }
      echo "copying OPEN_CODE_KEY (value not printed):"
    else
      read -rsp "OPEN_CODE_KEY: " key
      echo
      [ -n "$key" ] || { echo "empty, nothing stored" >&2; exit 1; }
    fi
    # `bash -c "$(…)"`, not `… | bash`: piping the script into bash would make its `read`
    # loop consume the script's own lines instead of the value arriving on stdin.
    printf 'OPEN_CODE_KEY=%s\n' "$key" | ssh "$HOST" "bash -c \"\$(echo $MERGE_ENV | base64 -d)\""
    unset key
    # Restart only if it is already running; a first-time setup continues with deploy.
    ssh "$HOST" "cd $REMOTE && [ -f docker-compose.yml ] && docker compose up -d --force-recreate >/dev/null 2>&1 && echo '  restarted' || true"
    ;;

  build)
    build
    docker images --filter=reference="$IMAGE" --format 'table {{.Repository}}\t{{.Tag}}\t{{.Size}}'
    ;;

  deploy)
    require_provisioned
    build
    # Ship the compose file too, so the server's copy is never ahead of the repo's.
    scp "$REPO/deploy/docker-compose.prod.yml" "$HOST:$REMOTE/docker-compose.yml"
    echo "shipping the image (gzipped in flight)…"
    docker save "$IMAGE:latest" | gzip -1 | ssh "$HOST" 'gunzip | docker load'
    echo "restarting…"
    ssh "$HOST" "cd $REMOTE && docker compose up -d"
    sleep 10
    "$SELF" status
    ;;

  expose)
    # Put linkedin.applybuddy.net on Caddy. Separate from deploy and run once: it depends
    # on DNS this script can't change, and getting it wrong burns Let's Encrypt's
    # failed-validation budget.
    #
    # The Caddyfile lives in the BIPPASS repo — bippass.sh deploy scp's it over the
    # server's copy, so a block added anywhere else disappears at the next BipPass deploy.
    # NOTE: this ships that whole file, so any other uncommitted edits in it go too.
    grep -q "^$SITE_HOST {" "$BIPPASS_CADDYFILE" || {
      echo "no '$SITE_HOST {' block in $BIPPASS_CADDYFILE" >&2
      echo "add the block from $REPO/deploy/Caddyfile.snippet first." >&2
      exit 1
    }
    resolved=$(dig +short "$SITE_HOST" A | tail -1)
    want=${HOST#root@}
    if [ "$resolved" != "$want" ]; then
      echo "$SITE_HOST resolves to '${resolved:-nothing}', not $want." >&2
      echo >&2
      echo "Point it at the droplet first, DNS-only (grey cloud) — Caddy's HTTP-01" >&2
      echo "challenge has to reach this origin, and Cloudflare's proxy intercepts it." >&2
      exit 1
    fi
    echo "$SITE_HOST -> $want, good."
    scp "$BIPPASS_CADDYFILE" "$HOST:$BIPPASS_REMOTE/Caddyfile"
    # Graceful: Caddy validates the new config first and keeps serving the old one if it
    # does not parse, so a bad Caddyfile cannot take bippass.com down here.
    ssh "$HOST" "cd $BIPPASS_REMOTE && docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile" \
      2>&1 | grep -viE '"level":"(info|warn)"' || true
    echo "reloaded. certificate issuance takes a few seconds:"
    sleep 10
    curl -sS -m 20 -o /dev/null -w "  %{http_code}  cert verify=%{ssl_verify_result} (0 = trusted)\n" "$SITE_ORIGIN/api/health" \
      || echo "  not answering yet — check: $SELF logs"
    ;;

  logs)
    ssh "$HOST" "cd $REMOTE && docker compose logs -f --tail=200"
    ;;

  status)
    ssh "$HOST" "cd $REMOTE && docker compose ps --format 'table {{.Service}}\t{{.Status}}'" || true
    echo
    echo "health, from inside the container:"
    ssh "$HOST" "docker exec $CONTAINER python -c \"import urllib.request; print('  ', urllib.request.urlopen('http://127.0.0.1:8000/api/health', timeout=5).read().decode())\"" \
      2>/dev/null || echo "  not running"
    echo "health, public:"
    curl -sS -m 10 -o /dev/null -w "  %{http_code} $SITE_ORIGIN\n" "$SITE_ORIGIN/api/health" 2>/dev/null \
      || echo "  no route yet — DNS, then: $SELF expose"
    echo
    deployed=$(ssh "$HOST" "docker inspect $CONTAINER --format '{{index .Config.Labels \"org.opencontainers.image.revision\"}}'" 2>/dev/null || echo "?")
    echo "deployed: ${deployed:-?}   local HEAD: $(revision)"
    echo
    # The whole point of the memory limit: this app can't take BipPass down with it.
    ssh "$HOST" "free -m | awk 'NR==1||/Mem:|Swap:/'; echo; docker stats --no-stream --format 'table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}\t{{.CPUPerc}}'"
    ;;

  backup)
    out=${2:-linkedin-poster-data-$(date +%Y%m%d-%H%M%S).tgz}
    ssh "$HOST" "docker run --rm -v linkedin-poster_lpdata:/data:ro alpine tar czf - -C /data ." > "$out"
    echo "saved $out ($(du -h "$out" | cut -f1))"
    ;;

  *)
    echo "usage: $SELF [shell|provision|keys [local]|build|deploy|expose|status|logs|backup [file]]" >&2
    exit 1
    ;;
esac
